export const products = [
  {
    id: 1,
    name: 'Candy',
    description: 'Description for Product 1',
    price: 19.99,
    imageUrl: 'assets/image/21.jpg',
  },
  {
    id: 2,
    name: 'Dettol',
    description: 'Description for Product 2',
    price: 24.99,
    imageUrl: 'assets/image/11.jpg',
  },
  {
    id: 3,
    name: 'Pepsi',
    description: 'Description for Product 3',
    price: 14.99,
    imageUrl: 'assets/image/13.jpg',
  },
  {
    id: 4,
    name: 'Water glass',
    description: 'Description for Product 1',
    price: 19.99,
    imageUrl: 'assets/image/14.jpg',
  },
  {
    id: 5,
    name: 'Watch',
    description: 'Description for Product 2',
    price: 24.99,
    imageUrl: 'assets/image/15.jpg',
  },
  {
    id: 6,
    name: 'Cycle',
    description: 'Description for Product 3',
    price: 14.99,
    imageUrl: 'assets/image/16.jpg',
  },
  {
    id: 7,
    name: 'Kurkure',
    description: 'Description for Product 1',
    price: 19.99,
    imageUrl: 'assets/image/17.jpg',
  },
  {
    id: 8,
    name: 'Lays',
    description: 'Description for Product 2',
    price: 24.99,
    imageUrl: 'assets/image/18.jpg',
  },
  {
    id: 9,
    name: 'Ring',
    description: 'Description for Product 3',
    price: 14.99,
    imageUrl: 'assets/image/19.jpg',
  },
  {
    id: 10,
    name: 'Toy',
    description: 'Description for Product 3',
    price: 14.99,
    imageUrl: 'assets/image/20.jpg',
  },
];
